defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    timeout_min: 600
    mem_gb: 4
  sweep:
    dir: /scratch/fy2019/multirun/${now:%Y-%m-%d}/${now:%H:%M:%S}
    subdir: ${hydra.job.override_dirname}

# Parameters relating to stock and option prices and quantities
init_stock_holdings: 0
init_option_holdings: 100
init_wealth: 0
gbm_mu: 0.02
gbm_sigma: 0.09
gbm_r: 0.0

# Parameters relating to reward function and action space
reward_kappa: 0.1
reward_clip_min: -200
reward_clip_max: 200
action_min: -100
action_max: 100

# Parameters relating to training
data_reuse_num_episodes: 10000
total_training_timesteps: 12500000
learning_rate: 0.001

# PPO model hyperparameters -- these should be iterated over (on the command-line) using multirun
# gamma: 0.95
# gae_lambda: 0.9
# ent_coef: 0.2
# vf_coef: 0.5
# max_grad_norm: 0.5
# net_arch: [32,32,32,32,32]

# DDPG model hyperparameters
gamma: 0.95
tau: 0.005
train_freq: 1
gradient_steps: -1
learning_starts: 100
net_arch: [32,32,32,32,32]
